export interface Area {
    objectid: number,
    gm_naam: string,
    aant_inw: number,
    aantal_hh: number,
    bev_dichth: number,    
    aant_man: number,
    aant_vrouw: number,
    opp_totaal: number,
    opp_land: number,
    opp_water: number,
    p_00_14_jr: number,
    p_15_24_jr: number,
    p_25_44_jr: number,
    p_45_64_jr: number,
    p_65_eo_jr: number,
    
    p_elek_tot: number,
    p_elek_app: number,
    p_elek_tus: number,
    p_elek_hoe: number,
    p_elek_21k: number,
    p_elek_vry: number,
    p_elek_onb: number
}
